// src/lib/components/PostCard.svelte
<script lang="ts">
  import type { BlogPost } from "$lib/blog/types";
  let { post, featured = false }: { post: BlogPost; featured?: boolean } = $props();
  const publishedDate = $derived(post.published_at ?? post.created_at);
</script>

<article class:post-card-featured={featured} class="post-card">
  <div class="post-card-copy">
    <div class="post-card-meta">
      <a href={`/blog?category=${encodeURIComponent(post.category)}`}>{post.category}</a>
      <time datetime={publishedDate}>{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(publishedDate))}</time>
    </div>
    <h2><a href={`/blog/${post.slug}`}>{post.title}</a></h2>
    {#if post.excerpt}<p>{post.excerpt}</p>{/if}
    <a class="post-card-read" href={`/blog/${post.slug}`}>Read story <span aria-hidden="true">→</span></a>
  </div>
</article>

// src/components/blog/post-card.tsx
import Link from "next/link";
import type { BlogPost } from "@/lib/blog/types";

export function PostCard({ post, featured = false }: { post: BlogPost; featured?: boolean }) {
  return (
    <article className={featured ? "post-card post-card-featured" : "post-card"}>
      <div className="post-card-copy">
        <div className="post-card-meta">
          <Link href={`/blog?category=${encodeURIComponent(post.category)}`}>{post.category}</Link>
          <time dateTime={post.published_at ?? post.created_at}>
            {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(
              new Date(post.published_at ?? post.created_at),
            )}
          </time>
        </div>
        <h2><Link href={`/blog/${post.slug}`}>{post.title}</Link></h2>
        {post.excerpt && <p>{post.excerpt}</p>}
        <Link className="post-card-read" href={`/blog/${post.slug}`}>Read story <span aria-hidden="true">→</span></Link>
      </div>
    </article>
  );
}
