// src/lib/components/RichEditor.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Editor, Extension, Node, mergeAttributes, type JSONContent } from "@tiptap/core";
  import StarterKit from "@tiptap/starter-kit";
  import Link from "@tiptap/extension-link";
  import Image from "@tiptap/extension-image";
  import Youtube from "@tiptap/extension-youtube";
  import Underline from "@tiptap/extension-underline";
  import TextAlign from "@tiptap/extension-text-align";
  import Placeholder from "@tiptap/extension-placeholder";
  import CharacterCount from "@tiptap/extension-character-count";
  import Highlight from "@tiptap/extension-highlight";
  import TaskList from "@tiptap/extension-task-list";
  import TaskItem from "@tiptap/extension-task-item";
  import { Table } from "@tiptap/extension-table";
  import TableRow from "@tiptap/extension-table-row";
  import TableHeader from "@tiptap/extension-table-header";
  import TableCell from "@tiptap/extension-table-cell";
  import Typography from "@tiptap/extension-typography";
  import { createClient } from "$lib/supabase/client";

  let { value = $bindable() }: { value: JSONContent } = $props();
  let editorElement: HTMLDivElement;
  let editor = $state<Editor | null>(null);
  let revision = $state(0);
  let uploading = $state<"image" | "video" | "audio" | null>(null);
  let uploadError = $state("");

  const CspTextAlign = TextAlign.extend({ addGlobalAttributes() { return [{ types: this.options.types, attributes: { textAlign: { default: this.options.defaultAlignment, parseHTML: (element) => { const alignment = element.getAttribute("data-text-align") || element.style.textAlign; return this.options.alignments.includes(alignment) ? alignment : this.options.defaultAlignment; }, renderHTML: (attributes) => attributes.textAlign ? { "data-text-align": attributes.textAlign } : {} } } }]; } });
  const CspTable = Table.extend({ renderHTML({ HTMLAttributes }) { const attributes = { ...HTMLAttributes }; delete attributes.style; return ["table", mergeAttributes(this.options.HTMLAttributes, attributes), ["tbody", 0]]; } });
  const CspTableCell = TableCell.extend({ renderHTML({ HTMLAttributes }) { const attributes = { ...HTMLAttributes }; delete attributes.style; return ["td", mergeAttributes(this.options.HTMLAttributes, attributes), 0]; } });
  const CspTableHeader = TableHeader.extend({ renderHTML({ HTMLAttributes }) { const attributes = { ...HTMLAttributes }; delete attributes.style; return ["th", mergeAttributes(this.options.HTMLAttributes, attributes), 0]; } });
  const AudioNode = Node.create({ name: "audio", group: "block", atom: true, draggable: true, addAttributes: () => ({ src: { default: null } }), parseHTML: () => [{ tag: "audio[src]" }], renderHTML: ({ HTMLAttributes }) => ["audio", mergeAttributes(HTMLAttributes, { controls: "true" })] });
  const VideoNode = Node.create({ name: "video", group: "block", atom: true, draggable: true, addAttributes: () => ({ src: { default: null } }), parseHTML: () => [{ tag: "video[src]" }], renderHTML: ({ HTMLAttributes }) => ["video", mergeAttributes(HTMLAttributes, { controls: "true" })] });
  const SectionGapNode = Node.create({ name: "sectionGap", group: "block", atom: true, draggable: true, addAttributes: () => ({ size: { default: "medium", parseHTML: (element) => ["small", "medium", "large"].includes(element.getAttribute("data-gap-size") ?? "") ? element.getAttribute("data-gap-size") : "medium", renderHTML: (attributes) => ({ "data-gap-size": ["small", "medium", "large"].includes(String(attributes.size)) ? attributes.size : "medium" }) } }), parseHTML: () => [{ tag: "div[data-section-gap]" }], renderHTML: ({ HTMLAttributes }) => ["div", mergeAttributes(HTMLAttributes, { "data-section-gap": "", role: "separator", "aria-label": "Section gap" })] });
  const ResizableMedia = Extension.create({ name: "resizableMedia", addGlobalAttributes() { return [{ types: ["image", "video", "audio", "youtube"], attributes: { mediaWidth: { default: 100, parseHTML: (element) => Math.min(100, Math.max(10, Math.round((Number(element.getAttribute("data-media-width")) || 100) / 5) * 5)), renderHTML: (attributes) => ({ "data-media-width": Math.min(100, Math.max(10, Math.round((Number(attributes.mediaWidth) || 100) / 5) * 5)) }) }, mediaLayout: { default: "standalone", parseHTML: (element) => element.getAttribute("data-media-layout") || "standalone", renderHTML: (attributes) => ({ "data-media-layout": attributes.mediaLayout }) } } }]; } });

  onMount(() => {
    editor = new Editor({ element: editorElement, extensions: [StarterKit.configure({ heading: { levels: [1, 2, 3] } }), Link.configure({ openOnClick: false, autolink: true, defaultProtocol: "https" }), Image.configure({ allowBase64: false }), Youtube.configure({ controls: true, nocookie: true }), Underline, CspTextAlign.configure({ types: ["heading", "paragraph"] }), Placeholder.configure({ placeholder: ({ node }) => node.type.name === "heading" ? "Write a clear section heading" : "Start writing, paste text, or use the toolbar to add media." }), CharacterCount.configure({ limit: 50000 }), Highlight, TaskList, TaskItem.configure({ nested: true }), CspTable, TableRow, CspTableHeader, CspTableCell, Typography, AudioNode, VideoNode, SectionGapNode, ResizableMedia], content: value, onUpdate: ({ editor }) => { value = editor.getJSON(); revision += 1; }, onSelectionUpdate: () => { revision += 1; }, editorProps: { attributes: { class: "editor-prose", spellcheck: "true", "aria-label": "Post body" } } });
    return () => editor?.destroy();
  });

  const normalizeUrl = (input: string) => { const trimmed = input.trim(); if (!trimmed) return ""; if (/^mailto:/i.test(trimmed) || /^https:\/\//i.test(trimmed)) return trimmed; if (/^http:\/\//i.test(trimmed)) return trimmed.replace(/^http:\/\//i, "https://"); return `https://${trimmed}`; };
  const active = (name: string, attrs?: Record<string, unknown>) => { void revision; return editor?.isActive(name, attrs) ?? false; };
  const run = (operation: (editor: Editor) => void) => { if (editor) operation(editor); };
  function promptLink() { if (!editor) return; const href = prompt("Paste a link URL", String(editor.getAttributes("link").href ?? "https://")); if (href === null) return; if (href.trim()) editor.chain().focus().extendMarkRange("link").setLink({ href: normalizeUrl(href) }).run(); else editor.chain().focus().extendMarkRange("link").unsetLink().run(); }
  function promptMedia(kind: "image" | "video" | "audio" | "youtube") { if (!editor) return; const source = prompt(`Paste an HTTPS ${kind} URL`); if (!source) return; const src = normalizeUrl(source); if (kind === "image") editor.chain().focus().setImage({ src, alt: prompt("Short image description", "") ?? "" }).run(); else if (kind === "youtube") editor.commands.setYoutubeVideo({ src, width: 1280, height: 720 }); else editor.chain().focus().insertContent({ type: kind, attrs: { src } }).run(); }
  async function upload(file: File, kind: "image" | "video" | "audio") { uploading = kind; uploadError = ""; try { const response = await fetch("/api/media", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filename: file.name, contentType: file.type, size: file.size }) }); const signed = await response.json() as { path?: string; token?: string; publicUrl?: string; error?: string }; if (!response.ok || !signed.path || !signed.token || !signed.publicUrl) throw new Error(signed.error ?? "Could not prepare upload"); const { error } = await createClient().storage.from("blog-media").uploadToSignedUrl(signed.path, signed.token, file, { contentType: file.type }); if (error) throw error; if (kind === "image") editor?.chain().focus().setImage({ src: signed.publicUrl, alt: file.name.replace(/\.[^.]+$/, "") }).run(); else editor?.chain().focus().insertContent({ type: kind, attrs: { src: signed.publicUrl } }).run(); } catch (error) { uploadError = error instanceof Error ? error.message : "Upload failed"; } finally { uploading = null; } }
  function updateMedia(attributes: { mediaWidth?: number; mediaLayout?: string }) { if (!editor) return; const type = (["image", "video", "audio", "youtube"] as const).find((item) => editor?.isActive(item)); if (type) editor.chain().focus().updateAttributes(type, attributes).run(); }
  const selectedMedia = $derived(((["image", "video", "audio", "youtube"] as const).find((type) => { void revision; return editor?.isActive(type); })));
  const mediaWidth = $derived(selectedMedia && editor ? Number(editor.getAttributes(selectedMedia).mediaWidth) || 100 : 100);
</script>

<div class="rich-editor">
  {#if editor}
    <div class="editor-toolbar" role="toolbar" aria-label="Post formatting">
      <div class="editor-toolbar-row">
        <div class="editor-toolbar-group" aria-label="History"><button type="button" onclick={() => run((e) => e.chain().focus().undo().run())}>Undo</button><button type="button" onclick={() => run((e) => e.chain().focus().redo().run())}>Redo</button></div>
        <div class="editor-toolbar-group" aria-label="Text style"><button type="button" class:is-active={active("paragraph")} onclick={() => run((e) => e.chain().focus().setParagraph().run())}>Text</button><button type="button" class:is-active={active("heading", { level: 1 })} onclick={() => run((e) => e.chain().focus().toggleHeading({ level: 1 }).run())}>H1</button><button type="button" class:is-active={active("heading", { level: 2 })} onclick={() => run((e) => e.chain().focus().toggleHeading({ level: 2 }).run())}>H2</button><button type="button" class:is-active={active("heading", { level: 3 })} onclick={() => run((e) => e.chain().focus().toggleHeading({ level: 3 }).run())}>H3</button><button type="button" class:is-active={active("blockquote")} onclick={() => run((e) => e.chain().focus().toggleBlockquote().run())}>Quote</button></div>
        <div class="editor-toolbar-group" aria-label="Inline formatting"><button type="button" class:is-active={active("bold")} onclick={() => run((e) => e.chain().focus().toggleBold().run())}>B</button><button type="button" class:is-active={active("italic")} onclick={() => run((e) => e.chain().focus().toggleItalic().run())}>I</button><button type="button" class:is-active={active("underline")} onclick={() => run((e) => e.chain().focus().toggleUnderline().run())}>U</button><button type="button" class:is-active={active("strike")} onclick={() => run((e) => e.chain().focus().toggleStrike().run())}>S</button><button type="button" class:is-active={active("code")} onclick={() => run((e) => e.chain().focus().toggleCode().run())}>Code</button><button type="button" class:is-active={active("highlight")} onclick={() => run((e) => e.chain().focus().toggleHighlight().run())}>Mark</button></div>
        <div class="editor-toolbar-group" aria-label="Alignment">{#each ["left", "center", "right", "justify"] as alignment}<button type="button" class:is-active={active("paragraph", { textAlign: alignment }) || active("heading", { textAlign: alignment })} onclick={() => run((e) => e.chain().focus().setTextAlign(alignment).run())}>{alignment}</button>{/each}</div>
      </div>
      <div class="editor-toolbar-row">
        <div class="editor-toolbar-group" aria-label="Structure"><button type="button" onclick={() => run((e) => e.chain().focus().toggleBulletList().run())}>Bullets</button><button type="button" onclick={() => run((e) => e.chain().focus().toggleOrderedList().run())}>Numbers</button><button type="button" onclick={() => run((e) => e.chain().focus().toggleTaskList().run())}>Checklist</button><button type="button" onclick={() => run((e) => e.chain().focus().setHorizontalRule().run())}>Rule</button>{#each ["small", "medium", "large"] as size}<button type="button" onclick={() => run((e) => e.chain().focus().insertContent([{ type: "sectionGap", attrs: { size } }, { type: "paragraph" }]).run())}>Gap {size[0].toUpperCase()}</button>{/each}</div>
        <div class="editor-toolbar-group" aria-label="Links and media"><button type="button" onclick={promptLink}>Link</button><button type="button" onclick={() => run((e) => e.chain().focus().unsetLink().run())}>Unlink</button>{#each ["image", "youtube", "video", "audio"] as kind}<button type="button" onclick={() => promptMedia(kind as "image" | "video" | "audio" | "youtube")}>{kind} URL</button>{/each}{#each ["image", "video", "audio"] as kind}<label class="editor-upload">{uploading === kind ? "Uploading…" : `Upload ${kind}`}<input type="file" accept={kind === "image" ? "image/jpeg,image/png,image/webp,image/gif" : `${kind}/*`} disabled={Boolean(uploading)} onchange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void upload(file, kind as "image" | "video" | "audio"); event.currentTarget.value = ""; }} /></label>{/each}</div>
        <div class="editor-toolbar-group" aria-label="Media layout"><button type="button" disabled={!selectedMedia} onclick={() => updateMedia({ mediaLayout: "left" })}>Wrap left</button><button type="button" disabled={!selectedMedia} onclick={() => updateMedia({ mediaLayout: "row", mediaWidth: Math.min(mediaWidth, 50) })}>Row</button><button type="button" disabled={!selectedMedia} onclick={() => updateMedia({ mediaLayout: "standalone" })}>No wrap</button><button type="button" disabled={!selectedMedia} onclick={() => updateMedia({ mediaLayout: "right" })}>Wrap right</button><label class="editor-media-size"><span class="editor-media-label">Width</span><span class="editor-range-control"><input type="range" min="10" max="100" step="5" value={mediaWidth} disabled={!selectedMedia} onchange={(event) => updateMedia({ mediaWidth: Number(event.currentTarget.value) })} /></span><span>{mediaWidth}%</span></label></div>
        <div class="editor-toolbar-group" aria-label="Tables"><button type="button" onclick={() => run((e) => e.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: true }).run())}>Table</button><button type="button" disabled={!active("table")} onclick={() => run((e) => e.chain().focus().addRowAfter().run())}>+ Row</button><button type="button" disabled={!active("table")} onclick={() => run((e) => e.chain().focus().addColumnAfter().run())}>+ Col</button><button type="button" disabled={!active("table")} onclick={() => run((e) => e.chain().focus().deleteTable().run())}>Del table</button></div>
      </div>
    </div>
  {/if}
  <div class="editor-document-wrap"><div bind:this={editorElement}></div></div>
  {#if editor}<div class="editor-footer-bar" aria-live="polite"><span>{editor.storage.characterCount.words()} words</span><span>{editor.storage.characterCount.characters()} characters</span><span>{Math.max(1, Math.ceil(editor.storage.characterCount.words() / 220))} min read</span></div>{/if}
  {#if uploadError}<p class="form-error editor-error" role="alert">{uploadError}</p>{/if}
</div>

// src/components/blog/rich-editor.tsx
"use client";

import { useState } from "react";
import { Extension, Node, mergeAttributes, type JSONContent } from "@tiptap/core";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Link from "@tiptap/extension-link";
import Image from "@tiptap/extension-image";
import Youtube from "@tiptap/extension-youtube";
import Underline from "@tiptap/extension-underline";
import TextAlign from "@tiptap/extension-text-align";
import Placeholder from "@tiptap/extension-placeholder";
import CharacterCount from "@tiptap/extension-character-count";
import Highlight from "@tiptap/extension-highlight";
import TaskList from "@tiptap/extension-task-list";
import TaskItem from "@tiptap/extension-task-item";
import { Table } from "@tiptap/extension-table";
import TableRow from "@tiptap/extension-table-row";
import TableHeader from "@tiptap/extension-table-header";
import TableCell from "@tiptap/extension-table-cell";
import Typography from "@tiptap/extension-typography";
import { createClient } from "@/lib/supabase/client";

const AudioNode = Node.create({
  name: "audio",
  group: "block",
  atom: true,
  addAttributes: () => ({ src: { default: null } }),
  parseHTML: () => [{ tag: "audio[src]" }],
  renderHTML: ({ HTMLAttributes }) => ["audio", mergeAttributes(HTMLAttributes, { controls: "true" })],
});

const VideoNode = Node.create({
  name: "video",
  group: "block",
  atom: true,
  addAttributes: () => ({ src: { default: null } }),
  parseHTML: () => [{ tag: "video[src]" }],
  renderHTML: ({ HTMLAttributes }) => ["video", mergeAttributes(HTMLAttributes, { controls: "true" })],
});

const ResizableMedia = Extension.create({
  name: "resizableMedia",
  addGlobalAttributes() {
    return [{
      types: ["image", "video", "audio", "youtube"],
      attributes: {
        mediaWidth: {
          default: 100,
          parseHTML: (element) => Number(element.getAttribute("data-media-width")) || 100,
          renderHTML: (attributes) => ({ "data-media-width": attributes.mediaWidth }),
        },
      },
    }];
  },
});

type MediaKind = "image" | "video" | "audio";
type BlockStyle = "paragraph" | "h1" | "h2" | "h3" | "quote" | "code";

async function uploadMedia(file: File) {
  const response = await fetch("/api/media", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ filename: file.name, contentType: file.type, size: file.size }),
  });
  const signed = (await response.json()) as { path?: string; token?: string; publicUrl?: string; error?: string };
  if (!response.ok || !signed.path || !signed.token || !signed.publicUrl) {
    throw new Error(signed.error ?? "Could not prepare upload");
  }
  const supabase = createClient();
  const { error } = await supabase.storage.from("blog-media").uploadToSignedUrl(signed.path, signed.token, file, {
    contentType: file.type,
  });
  if (error) throw error;
  return signed.publicUrl;
}

function normalizeUrl(value: string) {
  const trimmed = value.trim();
  if (!trimmed) return "";
  if (/^mailto:/i.test(trimmed)) return trimmed;
  if (/^http:\/\//i.test(trimmed)) return trimmed.replace(/^http:\/\//i, "https://");
  if (/^https:\/\//i.test(trimmed)) return trimmed;
  return `https://${trimmed}`;
}

function readTime(words: number) {
  return Math.max(1, Math.ceil(words / 220));
}

function ToolbarGroup({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="editor-toolbar-group" aria-label={label}>
      {children}
    </div>
  );
}

function ToolButton({
  label,
  title,
  active,
  disabled,
  onClick,
}: {
  label: string;
  title?: string;
  active?: boolean;
  disabled?: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      className={active ? "is-active" : undefined}
      aria-pressed={active}
      title={title ?? label}
      disabled={disabled}
      onMouseDown={(event) => event.preventDefault()}
      onClick={onClick}
    >
      {label}
    </button>
  );
}

export function RichEditor({ value, onChange }: { value: JSONContent; onChange: (value: JSONContent) => void }) {
  const [uploading, setUploading] = useState<MediaKind | null>(null);
  const [error, setError] = useState("");
  const [, refreshToolbar] = useState(0);

  const editor = useEditor({
    immediatelyRender: false,
    extensions: [
      StarterKit.configure({ heading: { levels: [1, 2, 3] } }),
      Link.configure({ openOnClick: false, autolink: true, defaultProtocol: "https" }),
      Image.configure({ allowBase64: false }),
      Youtube.configure({ controls: true, nocookie: true }),
      Underline,
      TextAlign.configure({ types: ["heading", "paragraph"] }),
      Placeholder.configure({
        placeholder: ({ node }) =>
          node.type.name === "heading"
            ? "Write a clear section heading"
            : "Start writing, paste text, or use the toolbar to add media.",
      }),
      CharacterCount.configure({ limit: 50000 }),
      Highlight,
      TaskList,
      TaskItem.configure({ nested: true }),
      Table.configure({ resizable: true }),
      TableRow,
      TableHeader,
      TableCell,
      Typography,
      AudioNode,
      VideoNode,
      ResizableMedia,
    ],
    content: value,
    onUpdate: ({ editor: currentEditor }) => {
      onChange(currentEditor.getJSON());
      refreshToolbar((revision) => revision + 1);
    },
    onSelectionUpdate: () => refreshToolbar((revision) => revision + 1),
    editorProps: {
      attributes: {
        class: "editor-prose",
        spellcheck: "true",
        "aria-label": "Post body",
      },
    },
  });

  if (!editor) return <div className="editor-loading">Loading editor...</div>;
  const activeEditor = editor;
  const words = activeEditor.storage.characterCount.words() as number;
  const stats = {
    words,
    characters: activeEditor.storage.characterCount.characters() as number,
    minutes: readTime(words),
  };
  const inTable = activeEditor.isActive("table");
  const canUndo = activeEditor.can().undo();
  const canRedo = activeEditor.can().redo();
  const selectedMedia = (["image", "video", "audio", "youtube"] as const).find((type) => activeEditor.isActive(type));
  const selectedMediaWidth = selectedMedia
    ? Number(activeEditor.getAttributes(selectedMedia).mediaWidth) || 100
    : 100;

  const blockStyle: BlockStyle = activeEditor.isActive("heading", { level: 1 })
    ? "h1"
    : activeEditor.isActive("heading", { level: 2 })
      ? "h2"
      : activeEditor.isActive("heading", { level: 3 })
        ? "h3"
        : activeEditor.isActive("blockquote")
          ? "quote"
          : activeEditor.isActive("codeBlock")
            ? "code"
            : "paragraph";

  async function handleFile(file: File, kind: MediaKind) {
    setUploading(kind);
    setError("");
    try {
      const url = await uploadMedia(file);
      if (kind === "image") {
        activeEditor.chain().focus().setImage({ src: url, alt: file.name.replace(/\.[^.]+$/, "") }).run();
      }
      if (kind === "video") activeEditor.chain().focus().insertContent({ type: "video", attrs: { src: url } }).run();
      if (kind === "audio") activeEditor.chain().focus().insertContent({ type: "audio", attrs: { src: url } }).run();
    } catch (uploadError) {
      setError(uploadError instanceof Error ? uploadError.message : "Upload failed");
    } finally {
      setUploading(null);
    }
  }

  function applyBlockStyle(nextStyle: BlockStyle) {
    const chain = activeEditor.chain().focus();
    if (nextStyle === "paragraph") chain.setParagraph().run();
    if (nextStyle === "h1") chain.toggleHeading({ level: 1 }).run();
    if (nextStyle === "h2") chain.toggleHeading({ level: 2 }).run();
    if (nextStyle === "h3") chain.toggleHeading({ level: 3 }).run();
    if (nextStyle === "quote") chain.toggleBlockquote().run();
    if (nextStyle === "code") chain.toggleCodeBlock().run();
  }

  function addLink() {
    const previous = activeEditor.getAttributes("link").href as string | undefined;
    const href = window.prompt("Paste a link URL", previous ?? "https://");
    if (href === null) return;
    if (!href.trim()) activeEditor.chain().focus().extendMarkRange("link").unsetLink().run();
    else activeEditor.chain().focus().extendMarkRange("link").setLink({ href: normalizeUrl(href) }).run();
  }

  function addImageUrl() {
    const src = window.prompt("Paste an HTTPS image URL");
    if (!src) return;
    const alt = window.prompt("Short image description", "") ?? "";
    activeEditor.chain().focus().setImage({ src: normalizeUrl(src), alt }).run();
  }

  function addYoutube() {
    const src = window.prompt("Paste a YouTube URL");
    if (src) activeEditor.commands.setYoutubeVideo({ src: normalizeUrl(src), width: 1280, height: 720 });
  }

  function addMediaUrl(kind: "video" | "audio") {
    const src = window.prompt(`Paste an HTTPS ${kind} URL`);
    if (src) activeEditor.chain().focus().insertContent({ type: kind, attrs: { src: normalizeUrl(src) } }).run();
  }

  return (
    <div className="rich-editor">
      <div className="editor-toolbar" role="toolbar" aria-label="Post formatting">
        <div className="editor-toolbar-row">
          <ToolbarGroup label="Document history">
            <ToolButton label="Undo" title="Undo" disabled={!canUndo} onClick={() => activeEditor.chain().focus().undo().run()} />
            <ToolButton label="Redo" title="Redo" disabled={!canRedo} onClick={() => activeEditor.chain().focus().redo().run()} />
          </ToolbarGroup>

          <ToolbarGroup label="Text style">
            <label className="editor-style-select">
              <span className="sr-only">Text style</span>
              <select value={blockStyle} onChange={(event) => applyBlockStyle(event.target.value as BlockStyle)}>
                <option value="paragraph">Normal text</option>
                <option value="h1">Title heading</option>
                <option value="h2">Section heading</option>
                <option value="h3">Small heading</option>
                <option value="quote">Quote</option>
                <option value="code">Code block</option>
              </select>
            </label>
          </ToolbarGroup>

          <ToolbarGroup label="Inline formatting">
            <ToolButton label="B" title="Bold" active={activeEditor.isActive("bold")} onClick={() => activeEditor.chain().focus().toggleBold().run()} />
            <ToolButton label="I" title="Italic" active={activeEditor.isActive("italic")} onClick={() => activeEditor.chain().focus().toggleItalic().run()} />
            <ToolButton label="U" title="Underline" active={activeEditor.isActive("underline")} onClick={() => activeEditor.chain().focus().toggleUnderline().run()} />
            <ToolButton label="S" title="Strikethrough" active={activeEditor.isActive("strike")} onClick={() => activeEditor.chain().focus().toggleStrike().run()} />
            <ToolButton label="Code" active={activeEditor.isActive("code")} onClick={() => activeEditor.chain().focus().toggleCode().run()} />
            <ToolButton label="Mark" title="Highlight" active={activeEditor.isActive("highlight")} onClick={() => activeEditor.chain().focus().toggleHighlight().run()} />
          </ToolbarGroup>

          <ToolbarGroup label="Paragraph alignment">
            <ToolButton label="Left" active={activeEditor.isActive({ textAlign: "left" })} onClick={() => activeEditor.chain().focus().setTextAlign("left").run()} />
            <ToolButton label="Center" active={activeEditor.isActive({ textAlign: "center" })} onClick={() => activeEditor.chain().focus().setTextAlign("center").run()} />
            <ToolButton label="Right" active={activeEditor.isActive({ textAlign: "right" })} onClick={() => activeEditor.chain().focus().setTextAlign("right").run()} />
            <ToolButton label="Justify" active={activeEditor.isActive({ textAlign: "justify" })} onClick={() => activeEditor.chain().focus().setTextAlign("justify").run()} />
          </ToolbarGroup>
        </div>

        <div className="editor-toolbar-row">
          <ToolbarGroup label="Lists and structure">
            <ToolButton label="Bullets" active={activeEditor.isActive("bulletList")} onClick={() => activeEditor.chain().focus().toggleBulletList().run()} />
            <ToolButton label="Numbers" active={activeEditor.isActive("orderedList")} onClick={() => activeEditor.chain().focus().toggleOrderedList().run()} />
            <ToolButton label="Checklist" active={activeEditor.isActive("taskList")} onClick={() => activeEditor.chain().focus().toggleTaskList().run()} />
            <ToolButton label="Rule" title="Horizontal rule" onClick={() => activeEditor.chain().focus().setHorizontalRule().run()} />
          </ToolbarGroup>

          <ToolbarGroup label="Links and media">
            <ToolButton label="Link" active={activeEditor.isActive("link")} onClick={addLink} />
            <ToolButton label="Unlink" disabled={!activeEditor.isActive("link")} onClick={() => activeEditor.chain().focus().unsetLink().run()} />
            <ToolButton label="Image URL" onClick={addImageUrl} />
            <ToolButton label="YouTube" onClick={addYoutube} />
            <ToolButton label="Video URL" onClick={() => addMediaUrl("video")} />
            <ToolButton label="Audio URL" onClick={() => addMediaUrl("audio")} />
            {(["image", "video", "audio"] as MediaKind[]).map((kind) => (
              <label className="editor-upload" key={kind}>
                {uploading === kind ? "Uploading..." : `Upload ${kind}`}
                <input
                  type="file"
                  accept={kind === "image" ? "image/jpeg,image/png,image/webp,image/gif" : `${kind}/*`}
                  disabled={Boolean(uploading)}
                  onChange={(event) => {
                    const file = event.target.files?.[0];
                    if (file) void handleFile(file, kind);
                    event.target.value = "";
                  }}
                />
              </label>
            ))}
          </ToolbarGroup>

          <ToolbarGroup label="Selected media size">
            {([25, 50, 75, 100] as const).map((width) => (
              <ToolButton
                key={width}
                label={`${width}%`}
                title={selectedMedia ? `Set selected ${selectedMedia} to ${width}% width` : "Select media in the post first"}
                active={Boolean(selectedMedia) && selectedMediaWidth === width}
                disabled={!selectedMedia}
                onClick={() => {
                  if (selectedMedia) activeEditor.chain().focus().updateAttributes(selectedMedia, { mediaWidth: width }).run();
                }}
              />
            ))}
          </ToolbarGroup>

          <ToolbarGroup label="Tables">
            <ToolButton label="Table" onClick={() => activeEditor.chain().focus().insertTable({ rows: 3, cols: 3, withHeaderRow: true }).run()} />
            <ToolButton label="+ Row" disabled={!inTable} onClick={() => activeEditor.chain().focus().addRowAfter().run()} />
            <ToolButton label="+ Col" disabled={!inTable} onClick={() => activeEditor.chain().focus().addColumnAfter().run()} />
            <ToolButton label="Del Row" disabled={!inTable} onClick={() => activeEditor.chain().focus().deleteRow().run()} />
            <ToolButton label="Del Col" disabled={!inTable} onClick={() => activeEditor.chain().focus().deleteColumn().run()} />
            <ToolButton label="Del Table" disabled={!inTable} onClick={() => activeEditor.chain().focus().deleteTable().run()} />
          </ToolbarGroup>
        </div>
      </div>

      <div className="editor-document-wrap">
        <EditorContent editor={activeEditor} />
      </div>

      <div className="editor-footer-bar" aria-live="polite">
        <span>{stats.words} words</span>
        <span>{stats.characters} characters</span>
        <span>{stats.minutes} min read</span>
        <span>Shortcuts: Ctrl+B, Ctrl+I, Ctrl+Z</span>
      </div>
      {error && <p className="form-error editor-error" role="alert">{error}</p>}
    </div>
  );
}
