// src/routes/blog/+page.svelte
<script lang="ts">
  import { BLOG_CATEGORIES, BLOG_NAME, BLOG_TAGLINE } from "$lib/blog/config";
  import BlogShell from "$lib/components/BlogShell.svelte";
  import PostCard from "$lib/components/PostCard.svelte";
  import type { PageProps } from "./$types";
  let { data }: PageProps = $props();
  const featured = $derived(data.posts[0]);
  const rest = $derived(data.posts.slice(1));
</script>

<svelte:head><title>{BLOG_NAME} | Renhet Studio</title><meta name="description" content={BLOG_TAGLINE} /><link rel="canonical" href="https://www.renhetstudio.com/blog" /></svelte:head>

<BlogShell profile={data.profile}>
  <header class="blog-hero"><div class="blog-hero-copy"><h1 class="blog-hero-enter">{BLOG_NAME}</h1><p class="blog-hero-tagline blog-hero-enter">{BLOG_TAGLINE}</p><a class="blog-hero-cta blog-hero-enter" href="#stories">Read the latest</a></div></header>
  <section id="stories" class="blog-stories">
    <div class="stories-heading"><h2 class="blog-scrub-copy">What we are making lately.</h2><form class="blog-filter" action="/blog"><label><span class="sr-only">Search stories</span><input name="q" value={data.query ?? ""} placeholder="Search stories" maxlength="80" /></label><label><span class="sr-only">Filter by category</span><select name="category" value={data.category ?? ""}><option value="">All categories</option>{#each BLOG_CATEGORIES as item}<option>{item}</option>{/each}</select></label><button type="submit">Filter</button></form></div>
    {#if !featured}
      <div class="blog-empty"><h2>No stories here yet.</h2><p>{data.category || data.query ? "Try a different filter." : "The first Renhet note is being prepared."}</p>{#if data.category || data.query}<a href="/blog">View all stories</a>{/if}</div>
    {:else}
      <div class="featured-grid"><PostCard post={featured} featured />{#each rest.slice(0, 2) as post}<PostCard {post} />{/each}</div>
      {#if rest.length > 2}<div class="post-accordion">{#each rest.slice(2) as post}<PostCard {post} />{/each}</div>{/if}
    {/if}
  </section>
</BlogShell>

// src/app/blog/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { BlogShell } from "@/components/blog/blog-shell";
import { BlogMotion } from "@/components/blog/blog-motion";
import { PostCard } from "@/components/blog/post-card";
import { BLOG_CATEGORIES, BLOG_NAME, BLOG_TAGLINE } from "@/lib/blog/config";
import { getPublishedPosts } from "@/lib/blog/data";
import { getCurrentProfile } from "@/lib/supabase/auth";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: BLOG_NAME,
  description: BLOG_TAGLINE,
  alternates: { canonical: "/blog" },
};

export default async function BlogPage({
  searchParams,
}: {
  searchParams: Promise<{ category?: string; q?: string }>;
}) {
  const params = await searchParams;
  const category = BLOG_CATEGORIES.includes(params.category as (typeof BLOG_CATEGORIES)[number])
    ? params.category
    : undefined;
  const [posts, profile] = await Promise.all([
    getPublishedPosts({ category, query: params.q }),
    getCurrentProfile(),
  ]);
  const [featured, ...rest] = posts;

  return (
    <BlogShell profile={profile}>
      <BlogMotion>
        <header className="blog-hero">
          <div className="blog-hero-copy">
            <h1 className="blog-hero-enter">{BLOG_NAME}</h1>
            <p className="blog-hero-tagline blog-hero-enter">{BLOG_TAGLINE}</p>
            <a className="blog-hero-cta blog-hero-enter" href="#stories">Read the latest</a>
          </div>
        </header>

        {/* <div className="category-marquee" aria-label="Blog categories">
          <div>
            {[...BLOG_CATEGORIES, ...BLOG_CATEGORIES].map((item, index) => (
              <span key={`${item}-${index}`}>{item}</span>
            ))}
          </div>
        </div> */}

        <section id="stories" className="blog-stories">
          <div className="stories-heading">
            <h2 className="blog-scrub-copy">What we are making lately.</h2>
            <form className="blog-filter" action="/blog">
              <label>
                <span className="sr-only">Search stories</span>
                <input name="q" defaultValue={params.q} placeholder="Search stories" maxLength={80} />
              </label>
              <label>
                <span className="sr-only">Filter by category</span>
                <select name="category" defaultValue={category ?? ""}>
                  <option value="">All categories</option>
                  {BLOG_CATEGORIES.map((item) => <option key={item}>{item}</option>)}
                </select>
              </label>
              <button type="submit">Filter</button>
            </form>
          </div>

          {!featured && (
            <div className="blog-empty">
              <h2>No stories here yet.</h2>
              <p>{category || params.q ? "Try a different filter." : "The first Renhet note is being prepared."}</p>
              {(category || params.q) && <Link href="/blog">View all stories</Link>}
            </div>
          )}

          {featured && (
            <div className="featured-grid">
              <PostCard post={featured} featured />
              {rest.slice(0, 2).map((post) => <PostCard post={post} key={post.id} />)}
            </div>
          )}

          {rest.length > 2 && (
            <div className="post-accordion">
              {rest.slice(2).map((post) => <PostCard post={post} key={post.id} />)}
            </div>
          )}
        </section>
      </BlogMotion>
    </BlogShell>
  );
}
